apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - ../../base/

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 39.0.1  # Update to desired version
    releaseName: traefik
    valuesFile: values.yaml
    includeCRDs: true