apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - namespace.yaml
  - cloudflare-secret.yaml
  - clusterissuer.yaml
  - certificate.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.19.3  # Update to desired version
    releaseName: cert-manager
    includeCRDs: true
    valuesInline:
      crds:
        enabled: true
        keep: true
