apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - ../../base/
  - cluster-issuer.yaml
  - certificate.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.19.1
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    valuesFile: values.yaml
