apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openbao

resources:
  - ../../base

helmCharts:
  - name: openbao
    repo: https://openbao.github.io/openbao-helm
    version: 0.25.5
    releaseName: openbao
    namespace: openbao
    valuesFile: values.yaml
